### ISSUE TITLE
how to create an admin (or privileged user)

### ISSUE THREAD

**Issue by jonsmirl** [aws-samples/aws-mobile-react-sample#28]
Porting issue from aws-amplify
proper technique to create an admin (or privileged user)

https://github.com/aws/aws-amplify/issues/83

**Comment by 8BitAron** [comment]
Roll Based Access Controls (rbac) using Cognito user groups would be nice

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html

An example of  how an Admin within a user group could elevate privileges of a list of users for a given user group

**Comment by mlabieniec** [comment]
tracking this feature here: https://github.com/aws/aws-amplify/issues/156
