### ISSUE TITLE
Change default account verification to Email vs SMS text 

### ISSUE THREAD

**Issue by 8BitAron** [aws-samples/aws-mobile-react-sample#32]
This demo is great but for someone starting out but you run into the SNS limit, and after your UserPool is created there is no way to change it. 

"Important: In order to send SMS messages to users to verify phone numbers or for MFA you must request a spending limit increase from Amazon SNS"

https://docs.aws.amazon.com/sns/latest/dg/sms_preferences.html
By default, the spend limit is set to 1.00 USD. If you want to raise the limit, submit an SNS Text Messaging case with AWS Support. For New limit value, enter your desired monthly spend limit. In the Use Case Description field, explain that you are requesting an SMS monthly spend limit increase. Typically, AWS Support processes your case within 2 business days. Depending on the spend limit you request and the complexity of your case, AWS Support might require an additional 3 - 5 days to ensure that your request can be processed.

Cheers

**Comment by zhulika** [comment]
Does anyone know if there a good reason why the MFA cannot be changed after the pool is created? It seems a pretty arbitrary restriction to this newbie who just got stone-walled by this very problem.

**Comment by mlabieniec** [comment]
the amazon cognito team has this in their backlog, thanks for the feedback.
