### ISSUE TITLE
Redeploy project

### ISSUE THREAD

**Issue by nkdevirl** [aws-samples/aws-mobile-react-sample#35]
After creating the project using

`awsmobile start my-project react`

Then making a few changes to the backend code

Then delete the project manually via the amazon console, ie, delete buckets, lamdba function and dynamodb tables.

Is there any way to redeploy the project again to the cloud from the my-project directory?

**Comment by UnleashedMind** [comment]
yes, if you have maintained the contents in the local `awsmobilejs/backend` folder, you can follow these steps to redeploy: 
- delete the `./awsmobilejs/info/project-info.json` file
- run `awsmobile init` in the root folder of the project, and the awsmobile-cli will ask if you want to create a backend project using the default or the specified features, choose the "specified features"
The the cli will then create another awsmobile project as the backend just the same as the one you had before.

**Comment by nkdevirl** [comment]
Thanks UnleashedMind for your response.

I did not get asked to use the specified features you mentioned. See the output below.
Do I need to do something differently?

`
rm awsmobilejs/.awsmobile/info/project-info.json 

awsmobile init

Please tell us about your project:
? Where is your project's source directory:  src
? Where is your project's distribution directory that stores build artifacts:  build
? What is your project's build command:  npm run-script build
? What is your project's start command for local test run:  npm run-script start

? What awsmobile project name would you like to use:  myProj

Successfully created AWS Mobile Hub project: myProj

retrieving the latest backend awsmobile project information
awsmobile project's details logged at: awsmobilejs/#current-backend-info/backend-details.json
awsmobile project's access information logged at: awsmobilejs/#current-backend-info/aws-exports.js
awsmobile project's access information copied to: src/aws-exports.js
awsmobile project's specifications logged at: awsmobilejs/#current-backend-info/mobile-hub-project.yml
contents in #current-backend-info/ is synchronized with the latest in the aws cloud

Success! your project is now initialized with awsmobilejs

   awsmobilejs/.awsmobile
     is the workspace of awsmobile-cli, please do not modify its contents

   awsmobilejs/#current-backend-info
     contains information of the backend awsmobile project from the last
     synchronization with the cloud

   awsmobilejs/backend
     is where you develop the codebase of the backend awsmobile project

   awsmobile console
     opens the web console of the backend awsmobile project

   awsmobile run
     pushes the latest development of the backend awsmobile project to the cloud,
     and runs the frontend application locally

   awsmobile publish
     pushes the latest development of the backend awsmobile project to the cloud,
     and publishes the frontend application to aws S3 for hosting

Happy coding with awsmobile!
`

**Comment by mlabieniec** [comment]
please open the issue on the [awsmobile-cli](https://github.com/aws/awsmobile-cli) repo.
