### ISSUE TITLE
Cannot see error messages in the login pages

### ISSUE THREAD

**Issue by jinman** [aws-samples/aws-mobile-react-sample#36]
I am unable to see the error messages in Login page. For example, when I login with the wrong password, it does not not show anything. I can see it in Google Developer Console but the UI does not show. Also, had to 'check unauthenticated identities' in Cognito console and add unauth role to make it work, even though I dont need unauthenticated identities. Not sure why. Any idea?

**Comment by powerful23** [comment]
@jinman The unauthenticated identities problem should be fixed in aws-amplify@beta maybe you can have a try on that version.
