### ISSUE TITLE
fsevents dependency breaks windows 10 support

### ISSUE THREAD

**Issue by dobon** [aws-samples/aws-mobile-react-sample#37]
Hi aws-mobile-react-sample maintainers,

The package 'chokidar'@1.7.0 is a dependency for this project, and it requires 'fsevents'@1.1.2 . Since fsevents doesn't work on windows and this is a required dependency, it breaks the build for windows with an error that amounts to "we couldn't install the required packages, so we aborted".

I was able to work around this by manually editing the npm-shrinkwrap.json and removing the fsevents dependency from chokidar and also removing the fsevents entry itself (which is pretty clumsy, but I was just testing), and the app appears to work fine without.

Am I a fool? Is this a known issue that isn't on the github tracker? Let me know if I can provide any additional details.

Best,
dobon

**Comment by mlabieniec** [comment]
@dobon fsevents is an os specific module and is specifically for mac os, issue on that here:
https://github.com/npm/npm/issues/11632
